server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 3.39.247.201
    port: 5672
    username: guest
    password: guest
#  profiles:
#    active: git
  cloud:
    config:
      server:
        git:
#          uri: file:///C:\Users\icore\Desktop\dowon\koscom-msa\git-local-repo
#          uri: file:///Users/dowonlee_1/Desktop/git/koscom-msa/git-local-repo2
#          uri: file:///C:\Users\KOSCOM\git\koscom-msa\git-local-repo2 # 형상관리가 됨
          uri: https://github.com/joneconsulting/spring-cloud-config
          default-label: master
      enabled: true
#        native: # just 파일
#          search-locations: file:///C:\Users\icore\Desktop\dowon\koscom-msa\git-local-repo # just 파일

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, refresh, metrics
