server:
  port: 0
#  port: ${random.int(50001,50002)}
spring:
  application:
    name: my-first-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${random.value}} # 0번포트 쓰면 랜덤 포트로 올라감. 하지만 인스턴스 id는 같으므로 인스턴스 id도 랜덤으로 생성
    prefer-ip-address: true
